version: '3'

services:
  lb:
    image: haproxy
    ports:
      - '8080:8080'
    volumes:
      - ./docker/haproxy:/usr/local/etc/haproxy
    depends_on:
      - ws
    networks:
      - pub-sub-redis-network

  ws:
    # image: wsapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=true
    deploy:
      replicas: 4
    networks:
      - pub-sub-redis-network
    depends_on:
      - rds

  rds:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - pub-sub-redis-network

networks:
  pub-sub-redis-network:
